const articles = [
  {
    id: 1,
    date:"22-09-2025",
    title:
      "L’eau : source de richesse, pouvoir et de conflits",
    text:
      "​Tous les pays ne sont pas égaux face à l’accès à l’eau, alors même qu’elle est un bien commun. On le voit de par la distribution inégale des rivières, des lacs, des installations en eau potable ou la richesse des nappes phréatiques des pays. En 2022, ce sont surtout les pays d’Afrique centrale, d'Asie de l’Est et du Sud qui souffrent plus des obstacles à l’accès à l’eau puisque plus de 1 million de leur population ne bénéficient pas d’installation en eau potable. Ces mêmes pays seront d’ailleurs de plus en plus exposés au stress hydrique d’ici 2040. Pour pallier à ce problème, il faut d’abord en connaître ses conditions d’apparition : changement climatique lié aux sécheresses et inondations, croissance démographique, manque de projets d’installations en eau potable. C’est dans ces contextes socio-environnementaux que les barrages apparaissent comme la solution permettant d’anticiper le problème du manque d’eau. Ils permettent aux États de reprendre la main sur l’eau en créant des réserves, que ce soit pour l’irrigation (48 % des barrages à but unique), l’hydroélectricité (17 %), l’approvisionnement en eau (13 %), le contrôle des crues (10 %), données de fin 2024.",
    subtitle1:
      "L’EAU FACTEUR DE PUISSANCE",
    text1:
    "​Un travail de la Banque mondiale datant de 2022 a démontré la relation positive existant entre l'évolution des réserves en eau et la croissance économique. Selon l’organisation, la croissance sous-entend une demande plus accrue en eau, et, dès lors que s’observe une diminution de l’eau, cela « se traduit par un ralentissement de la croissance ». En tant que « facteur vital », l’eau est nécessaire pour soutenir les pays en voie de développement. ​La Chine apparaît, pour ces États, comme un partenaire de choix pour la construction de barrages, on en retrouve d’ailleurs beaucoup sur le fleuve Lancang-Mékong. Une collaboration avec les pays d’Asie du Sud-Est qui s’inscrit dans les nouvelles routes de la soie et qui bénéficie non seulement au pays d’accueil de ces projets de construction (plus grande autonomie et sécurité énergétique, création d’emploi, formation de locaux), mais aussi à la Chine qui récolte les bénéfice de baux de long-terme ou des droits d’exploitation comme au Laos. De plus, ces infrastructures hydrauliques permettent de créer un marché régional attractif où la Chine, la Thaïlande et le Vietnam sont les principaux importateurs d’énergie hydraulique, alors que le Cambodge, le Laos et le Myanmar sont les principaux exportateurs. Ces projets près de la frontière chinoise permet d’accroître la connectivité entre le pays et ses voisins du sud-est. Ces projets sont aussi soutenus par la Banque Asiatique de Développement. ​L’eau permet aussi aux pays en pleine croissance, comme aux Émirats Arabes Unis où, en moyenne, chaque habitant consomme chaque jour 550L d’eau contre 870 L/jour pour un habitant de Las Vegas (250L/jour pour la moyenne mondiale).Dans les sociétés innovantes et de plus en plus connectées et urbanisées, la demande en eau ne fait que s’accroître. Il faut bien rafraîchir les data-centers qui sont plus nombreux, notamment du fait du boom de l’intelligence artificielle. L’Agence internationale de l'énergie (AIE) estime, dans son dernier rapport Energy and AI, publié en avril 2025, que les data centers ont consommé environ 560 milliards de litres d’eau à l’échelle mondiale en 2023. Un chiffre qui, selon eux, pourrait plus que doubler d’ici à 2030, pour atteindre près de 1 200 milliards de litres par an (source).",
    subtitle2:
    "L’EAU ÉCHAUDÉE",
    text2:
    "La construction de ces barrages apparaît d’une part, comme une aubaine tant économique qu’énergétique pour les pays en voie de développement ou en croissance accrue. D’autre part, ils présentent une opportunité d’influence pour les bailleurs de fonds des projets de construction. Malgré tout, les barrages génèrent des tensions dans la mesure où leur existence engendre des conséquences sur les économies voisines et dans la région. ​Du fait qu’elle est une ressource vitale, l’eau est un levier stratégique sur lequel un adversaire peut s’appuyer pour atteindre une nation. La destruction du barrage de Kakhovka en 2023 par la Russie (selon le Parlement Européen) ou par l’Ukraine (selon la Russie) affecte tant les populations et l’agriculture de Crimée, que la centrale nucléaire de Zaporijia qui utilisait le réservoir pour son système de refroidissement. ​Dans le cas du différend entre le l’Éthiopie, le Soudan et l’Égypte, l’eau n’est pas un moyen d’affecter un autre pays (car ces états ne sont pas en guerre), mais elle est, elle-même, une source de tensions. À l’origine de la dispute : la construction du grand barrage de la Renaissance menée par l’Éthiopie depuis 2011, et finalisée cette année. La présence d’une telle infrastructure sur le Nil bleu (source éthiopienne du Nil) affecte les apports en eau en Égypte et au Soudan. D’autant plus que les pays voisins de l’Éthiopie nourrissent un désaccord sur le prélèvement et le remplissage du réservoir (les éthiopiens optant pour un remplissage plus rapide que les autres). Citons aussi, dans le cas de l’eau génératrice de conflit, celui de la guerre de l’eau entre le Pakistan et l’Inde, encore d’actualité en 2025 alors qu’un traité de distribution a été conclu entre les deux pays en 1960. La situation est si critique que la Banque mondiale, qui a organisé les négociations pour le traité de 1960, finance des projets de barrages de recharge dans ces deux pays identifiés comme étant très vulnérables aux sécheresses.",
    subtitle3:
    "ASPECT ÉCONOMIQUE",
    text3:
    "​Là où la distribution de l’eau est un sujet qui nourrit des tensions entre certains États, elle permet à d’autres (via les barrages ou le contrôle sur les cours d’eau, les infrastructures) d’en tirer des bénéfices économiques et énergétiques. Dans ce domaine, la Chine excelle puisqu’en 2021 elle représente 30,1 % de la production d’électricité hydraulique mondiale. Le Brésil, qui a construit le plus grand barrage en Angola, se classe deuxième, produisant 9,2 % de l’électricité hydraulique mondiale (63,5 % à l’échelle brésilienne). ​En plus d’être liés à des marchés (celui de l’énergie, de la construction), les barrages apparaissent comme une solution quant aux entraves au commerce maritime. C’est le cas au canal de Panama, où transite 6 % du commerce mondial, puisque le passage est compromis du fait du changement climatique. C’est-à-dire que les plus gros navires ne peuvent passer que par le centre du canal et cela s’empire d’année en année. Afin de résoudre ce problème, le gouvernement du Panama souhaite construire un barrage sur le Rio Indio pour assurer d’avantage de transits. Ce projet entend aussi offrir une solution face aux sécheresses de plus en plus fréquentes, afin de sécuriser la vie des locaux. Cela dit, la réalisation sous-entend le déplacement de population.",
    subtitle4:
    "ENVIRONNEMENT",
    text4:
    "​Si les barrages apparaissent comme la solution de premier choix, elle est toutefois limités. Ces constructions s’avèreraient bien être une fausse bonne idée : une fois installées sur un cours de rivière, elles favorisent en effet l’évaporation. Par exemple, à Madagascar, Action Contre la Faim en a bien pris note et a donc mis en place un ingénieux système de barrage de sable. Le sable permet non seulement de filtrer naturellement l’eau mais aussi de réduire l’effet d’évaporation de 80 % par rapport à un barrage classique. En effet, l’eau est une denrée renouvelable dans une certaine mesure puisqu’environ la moitié de l’eau de pluie s’évapore. Depuis 2022 l’ONU prévient d'une crise imminente de l’eau tout en soulignant la gravité des périodes de sécheresse. Selon le World Resources Institute, la moitié de la population mondiale subit déjà un stress hydrique « élevé » au moins un mois par an ; et au Moyen-Orient ou en Afrique du Nord, 83 % de la population est exposée à un stress hydrique très important. ​Cette solution de trois barrages de sable à Madagascar s’avère peu coûteuse mais reste une réponse locale qui permet à un village de vivre de son agriculture, de cuisiner et de boire ; ceci alors que la population mondiale s’urbanise. ​S’ils répondent à des risques environnementaux, les barrages peuvent également en créer, notamment lorsqu’ils sont mal entretenus ou exposés à des catastrophes naturelles comme des séismes (risque d’éboulement, d’inondation, de tsunami)."
  },
  {
    id: 2,
    date:"27-08-2025",
    title:
      "Sociétés militaires privées : symptôme de l’externalisation de la guerre.",
    text:
      "​Le temps du monopole de la violence légitime alloué aux États est révolu. Les États ne s’appuient pas que sur des acteurs externes pour renforcer leur compétitivité dans le monde de l’innovation technologique. Les gouvernements font aussi appel à des acteurs externes issus du milieu sensible qu’est la défense. Ici, il est question de s’intéresser au phénomène d’externalisation des activités d’interventions militaires via des sociétés militaires privées (SMP). Si le mercenariat peut être confondu avec les SMP, cela dit le premier est illégal, le second est reconnu par la communauté internationale. Les mercenaires ne bénéficient pas d’un statut protégé par les conventions de Genève (Protocole additionnel aux conventions de Genève, 1977). Ces derniers ne sont pas liés à une armée régulière et les combattants agissent selon des motivations individuelles, souvent pécuniaires, pour le compte d’un État qui les embauche. Tant des critères qui peuvent s’appliquer aux employés de SMP, complexifiant ainsi leur distinction. ​A l’instar des SMP, elles sont encadrées de manière non contraignante par le document de Montreux (2008), qui adresse aux signataires quelques recommandations quant aux obligations de ces entités. ​L’appel à ces entreprises privées pour la réalisation d’opérations, autrefois domaine de chasse gardée des États, s’inscrit dans un contexte de transformation de la guerre vers une forme hybride. Face ces changements, la France doit s’adapter : ​« L’externalisation est devenue une réalité. Certaines de nos armées pratiquent la sous-traitance, la privatisation pour des opérations cinétiques ou tout simplement pour la protection armée en zone à risques. La France avait évoqué l’idée de travailler dans ce sens. Le rapport des deux députés Jean-Claude Viollet et Christian Ménard date de février 2012. En dix ans, nous n’avons pas beaucoup avancé sur la manière d’investir dans le champ des entreprises de services de sécurité et de défense – SMP, société militaire privée. » (source) ​Le guide sur l’externalisation définit l’externalisation en tant qu’« opération contractuelle impliquant un partenariat plus ou moins étroit, par lequel un organisme de la Défense décide de confier ou de transférer avec obligation de résultat à une structure externe au département une fonction, un service ou une activité qu'il assurait antérieurement, ce qui peut parfois impliquer des transferts d'actifs ».",
    subtitle1:
      "Historique",
    text1:
    "Ce phénomène d'externalisation, qui sous-entend la privatisation et la contractualisation partielle de la guerre, est en expansion, notamment depuis la chute du bloc soviétique. La première forme de SMP est apparue en Afrique du Sud, en 1989 (Exécutive Outcomes). Une entreprise qui mène, dès 1992, des opérations de sécurisation auprès des firmes pétrolières situées en Angola. C’est aussi sur le continent africain que la plus connue des SMP, Wagner, a permis à la Russie de nourrir une certaine influence. Sous Gorbatchev, puis sous Eltsine, la priorité politique était de se concentrer sur la nation, et non sur des opérations extérieures en Afrique jugées trop coûteuses. L’utilisation des SMP est répandue et n’est pas attribuable uniquement aux régimes non-démocratiques. On les retrouve au sein des USA (Blackwater), en Ukraine (Antonov logistics SALIS, une SMP qui a permis à complété les rangs des forces françaises opérant pour Serval et Barkhane). ​La Chine, état unitaire, y a également recours. Cela dit, le pays fait figure de contradiction face au paysage des SMP occidentales. Premièrement parce que leur coût est plus faible, en comparaison aux entreprises de sécurité étrangères. Comme le fait Gazprom avec Fakel et Flamya, la Chine envoie ces forces privées afin de sécuriser ses activités économiques, autour de ses nouvelles routes de la soie. Si la Chine a légalisé les activités des SMP en 2011, ce n’est toujours pas le cas pour la Russie, qui ne reconnaît pas sa proximité avec le groupe Wagner. ​Dans le cas chinois, la guerre ne se privatise pas, l’État ne laisse pas la main à des acteurs privés concernant son complexe militaro-industriel. C’est même l’inverse du phénomène d’externalisation qui s’y produit : le contrôle étatique s’étend sur les activités privées (collectivisme). Dans les états occidentaux (à tendance individualiste), les entreprises du domaine technologique ou militaro-industriel sont en droit de conserver leur position politique vis-à-vis de faits internationaux. ​L’externalisation laisse la place à l’intervention d’acteurs privés, cela contribue à la libéralisation de la guerre au sens où, sauf contre-indication de l’ONU ou nationale, les entreprises peuvent toujours contracter avec des nations étrangères. Le mouvement inverse (la nationalisation d’activités privées) suscite des tensions. Cela a été le cas lors de la nationalisation du canal de Suez sous Nasser, qui a eu pour effet de voir intervenir militairement français et anglais. Autre exemple : la crainte et la méfiance grandissante des USA envers l'’'Indonésie de Sukarno, étant donné que celui-ci entend nationaliser les activités pétrolières en 1945.",
    subtitle2:
    "Cause de l’externalisation",
    text2:
    "L’externalisation que l’on constate dans les interventions en temps de guerre s’explique par plusieurs facteurs : ​Premièrement par la politique du « war from behind », un concept renvoyant à la participation états-unienne lors de l’intervention multilatérale en Libye en 2011, et qui traduit une volonté politique de faire la guerre discrètement. Cette stratégie permet de préserver l’image d’un pays, les gouvernements n’envoient pas ses « garçons » au front, comme ce fut le cas lors de la guerre du Vietnam. Lorsque sont envoyés des contractuels, professionnels de la guerre, le gouvernement se garde l’option de ne pas reconnaître leur responsabilité sur leurs agissements. On assiste donc à l’avènement des guerres par procuration où l’on ne fait pas la guerre mais où on fait faire la guerre. Cela se traduit par l’envoi de matériel, de formateurs militaires, de financement (comme le fait l’Iran avec le Hezbollah). De plus, les revenus que les SMP génèrent en mission à l’étranger peuvent servir à l’effort de guerre national. C’est le cas de Wagner, qui réserve une partie de ses dépenses pour équiper ses hommes positionnés en Ukraine. Aussi par élan de patriotisme, de nombreux combattants de Wagner ont, à la mort de leur chef Prigojine, rejoint la Garde nationale. ​Secondement, la raison économique. Les États auraient recours aux contractuels par nécessité plutôt que par volonté. Le manque de personnel et des questions budgétaires contraignent la France à se tourner vers l’option de l’externalisation au début du XXIᵉ siècle.C’est-à-dire que suite à l’implosion du bloc soviétique, les États réduisent leur budget alloué à la défense, c’est le cas non seulement de la France, mais également des USA et du Royaume-Uni. Ainsi, dans la France sous Mitterrand, on préfère investir dans le  welfare plutôt que dans le warfare. ​Troisièmement, la raison contextuelle « d’instabilité mondiale et de préparation à la haute intensité » où « les États membres de l’OTAN se doivent de multiplier leurs capacités militaires malgré les contraintes budgétaires inhérentes aux crises successives qui ont frappé le monde (Covid-19) et l’Europe plus spécifiquement (énergie) » (source). En d’autres termes, depuis la crise de l’État-nation (Bertrand Badie), les États se doivent de recourir à d’autres moyens pour maintenir leur pouvoir, ces autres moyens incluant les acteurs externes, dont les SMP.",
    subtitle3:
    "Les problèmes de la zone grise",
    text3:
    "​Même s’il existe le document de Montreux, et que certains États ont légalisé les SMP, ces dernières n’en restent pas moins des entités peu transparentes. Déjà, parce que leurs activités s’apparentent souvent à celles du mercenariat. Par ailleurs, il existe très peu de données officielles et précises sur leur activité, leur composition, leur lieu d’opération, leur contrat et revenu. ​Enfin se pose la question de la responsabilité quant à leurs actes. Qui est responsable des exactions commises par une SMP opérant à l’étranger et qui n’est pas reconnue par son pays d’origine ? Voir l’article de Forbidden Stories sur « les prisons secrètes » de Wagner au Mali.",
    subtitle4:
    "Externalisation économique",    
    text4:
    "​Le contrat que les SMP passent avec l’État est un contrat gagnant-gagnant assurant rémunération aux contractuels et une intervention discrète pour le gouvernement. Les SMP ne sont pas les seuls acteurs externes, symptôme de l’externalisation de la guerre. Il y a les entreprises de l’armement assez influents pour soutenir des projets et stratégies de défense nationale (comme l’ont fait les nombreuses nouvelles entreprises du drone en Ukraine), mais aussi pour remporter des appels d’offres émis par des États étrangers. Citons le français Thales et le belge Proximus qui, cet été 2025, remportent l’offre de modernisation de l'agence d'information et de communication de l’Otan. Ou encore MSubs, une entreprise britannique qui a développé le drone sous-marin surnommé Excalibur que la Royal Navy a testé à l’été 2025, depuis l’Australie. Ce marché de l’armement permet à toutes nations de se doter, si elles en ont les moyens, des équipements militaires performants. Parfois, dans un contrat de vente, l’État acheteur est en mesure de bénéficier du transfert de technologie du matériel, des ressources qui lui permet de construire sur son sol ses propres équipements. ​Le monde du renseignement est également investi par des acteurs privés qui opèrent pour les gouvernements. Palantir en est un exemple. L’entreprise nord-américaine fournit des services (outils d’analyse quantité massive de données, de détection de combattants sur images de drones par exemple) à des services de renseignement étrangers (dont la DGSI) et des services états-uniens. ​La guerre dans le monde post guerre froide est également celle se jouant entre des acteurs privés dotés de moyens financiers, de brevets et de technologies précieuses pour les États. C’est ainsi que, dans le but de protéger ses savoirs, les États-Unis de Trump restreignaient en 2020 l’arrivée d’étudiants chinois dans les universités du pays (suspension et révocation de visa). La justification de cette mesure tient dans la considération de la civil-military fusion strategy. Une façon de pensée à la chinoise, qui vise à envisager la recherche en termes de double-avancée, dans les domaines économique et militaire. L’affrontement des avancées en matières d’innovation s’observe actuellement dans le domaine de l’intelligence artificielle, une course au « meilleur »  qui rappelle la course à l’espace du temps où le monde se divisait en deux",
    sources:
    "À lire : https://www.portail-ie.fr/univers/enjeux-de-puissances-et-geoeconomie/2023/lexternalisation-des-fonctions-de-soutien-de-larmee-une-tendance-qui-questionne-sur-notre-independance-strategique-a-long-terme/" 
  },
  {
    id: 3,
    date:"02-03-2026",
    title:
      "La défense aérienne, un enjeu européen",
    text:
      "Les guerres en Ukraine et entre Israël et l’Iran ont démontré l’importance de la composante aérienne militaire dans les théâtres d’opérations. Parmi ces équipements, les drones FPV (first-person view) ont changé la manière de faire la guerre, au point de devenir la première cause de perte d’effectifs en 2025. La composante aérienne militaire est utilisée pour la réalisation d’objectifs divers selon les contextes : la défense antiaérienne, l’emprise territoriale, la destruction ciblée de personnes, de systèmes de défense ennemis, ou la destruction d’infrastructures critiques, comme l’exemplifient les ciblages israéliens des sites de Natanz et Fordo. Les UAV (unmanned aerial vehicles) ne sont qu’un exemple de la composante aérienne militaire. Les missiles balistiques, les missiles hypersoniques, les radars, les avions de combat et de reconnaissance en font également partie. Face à l’importance de la composante aérienne militaire, l’Europe doit se doter des moyens militaires de défendre son territoire et de répondre aux menaces que représentent les arsenaux aériens des puissances hostiles. Or, le continent est encore trop dépendant de l’industrie états-unienne (I). Une stratégie réaliste tournée vers un système de défense et de dissuasion aérienne est nécessaire afin d’assurer la sécurité régionale de l’Europe (II).",
    subtitle1:
      "I.Dans un monde où l’intérêt pour le matériel militaire aérien grandit, l’Europe est encore trop dépendante des États-Unis ",
    text1:
    "Alors que l’intérêt global pour la dissuasion aérienne grandit (A), l’Europe se trouve encore dépendante des États-Unis, dont le soutien historique est devenu incertain (B).",
    subtitle2:
    "A) L’intérêt mondial pour les équipements de dissuasion aérienne s’est fait plus fort …<br>1.… Notamment par la prépondérance des drones ",
    text2:
    "Dans son analyse pour l’IRIS, la chercheuse Julia Tomasso explique l’intérêt du recours aux drones par trois caractéristiques : leur faible coût, le fait qu’ils permettent d’optimiser les ressources et de s’adapter au contexte géopolitique. C’est pour ces avantages que l’Ukraine utilise des Bayraktar TB2 turcs sur son front contre la Russie, qui elle utilise des Shahed-136 iraniens (produits pour environ $ 20 000 l’unité). Aux TB2 utilisés par l’Ukraine s’ajoutent les drones assemblés par les civils et acheminés près du front. Ces petits drones non conventionnels ont été l’élément central de l’opération Spiderweb qui a détruit à moindre coût des équipements russes. Le faible coût de fabrication des drones permet de réduire l’asymétrie entre États adverses. L’autre avantage des drones est leur furtivité. Grâce à leur petite taille, les UAV, et notamment les drones par fibre optique, sont difficilement détectables et sont redoutables contre des chars ou des équipements de défense aérienne. Pour les auteurs de « Why Drones Have Not Revolutionized War: The Enduring Hider-Finder Competition in Air Warfare » les drones ne sont pas intrinsèquement révolutionnaires mais ils permettent l’émergence d’une nouvelle dynamique de « hider-finder competition between air defense and air penetration ». Afin d’optimiser l’usage des drones, il faut d’une part accorder une attention particulière à la formation des pilotes. D’autre part, l’armée doit évaluer l’importance et l’efficacité de la composante aérienne militaire de l’État adverse. La composante aérienne militaire moderne de l’Azerbaïdjan (et renforcée par l’aide turque), couplée à des batteries de missiles sol-air arméniennes obsolètes expliquent en partie le fait que ce soit l’Azerbaïdjan qui a dominé le théâtre des opérations.",
    subtitle3:
    "2. Le programme militaire russe s’intensifie à mesure que l’Ukraine et ses alliés résistent.",
    text3:
    "Comme l’indiquait le président français lors de son dernier discours aux ambassadeurs, le programme militaire russe s’est « fortement durci » depuis le début de l’invasion en Ukraine, incluant les forces aériennes russes (VKS). Lors de la phase initiale du conflit, la Russie a réussi à détruire les systèmes de défense aérienne ukrainiens et à s’emparer de zones à l’est et au nord de Kiev. Toutefois, l’attaque surprise opérée par la Russie n’a pas eu les conséquences espérées par le Kremlin. Le pays a progressivement renforcé le déploiement de sa composante aérienne militaire pour atteindre ses objectifs territoriaux en Ukraine : 350 avions de combat ont été déployés depuis 2022. La Russie produit sur son sol, selon un rapport russe de 2025, des drones Shahed-136 (rebaptisés depuis Geran 2) à hauteur de 2 700 unités par mois (IISS, 2025). La présence russe dans l’espace aérien européen n’est pas un phénomène nouveau. En 2014, l’OTAN avait procédé à 150 interceptions aériennes en mer Baltique, contre 4 en 2010 et 47 en 2013 (ibid). Des opérations de démonstration de capacités aériennes menées par la Russie et par l’Occident, dans l’espace européen, ont été détectées des deux bords. Ces activités impliquaient des avions de reconnaissance (Tu-22M3 et Tu-95MS pour la Russie, le RC-135U Rivet Joint états-unien pour le Royaume-Uni). Au-delà des activités de reconnaissance, l’exhibition des missiles Oreshnik par la Russie représente un défi majeur pour les armées européennes, tant par le risque qu’ils représentent pour la sécurité régionale que par le fait que peu d’informations à leur propos sont accessibles. Les Oreshnik sont capables de transporter plusieurs ogives, nucléaires ou non nucléaires, ce qui les rend d’autant plus imprévisibles. Aux côtés des nouveaux équipements militaires aériens (l’Oreshnik depuis 2024, le drone ZALA Lancet depuis 2020), la Russie continue de faire usage de matériel plus traditionnel, datant parfois de la période soviétique (les missiles Raduga Kh-101, Raduga Kh-32, Tu-22M3 avec les Raduga Kh-22, les missiles Novator 3M14, 9M728, 9M729, ou le 3M22 Tsirkon).",
    subtitle4:
    "B) La dépendance européenne envers les États-Unis <br> 1.Le premier partenaire stratégique de l’Europe",    
    text4:
    "« Nous dépendons de la base industrielle et technologique de défense américaine » (le président français, lors du dernier discours adressé aux ambassadeurs). Pour assurer sa défense antiaérienne, l’Europe a recours aux équipements américains tels que le système mobile Patriot, qui est importé par l’Allemagne, la Grèce, les Pays-Bas, la Pologne, la Roumanie, l’Espagne et la Suède. La Norvège et l’Allemagne vont plus loin dans leur partenariat avec les États-Unis, en s’associant dans le domaine industriel. C’est ainsi que collaborent Raytheon et MBDA Deutschland pour doubler la production des intercepteurs PAC-2 GEM-T. À l’instar de la Norvège, Kongsberg Defence & Aerospace et Raytheon ont développé ensemble NASAMS (National Advanced Surface-to-Air Missile System), un système de défense sol-air déjà en service en Norvège, Espagne, Finlande, Hongrie, Lituanie et aux Pays-Bas. La part de l’Europe dans la somme des contrats d’acquisition passés par les membres de l’OTAN, qui est de 9,7 % entre 2018 et 2021 et 57,9 % entre 2022 et 2025, illustre sa dépendance aux États-Unis mais témoigne également d’un réveil sécuritaire européen. Les États-Unis restent, entre ces périodes, le premier pays à passer le plus de contrats d’acquisition, dans le domaine aérospatial, avec un investissement de 60 000 millions de dollars entre 2018 et 2021 et environ 95 000 millions de dollars entre 2022 et 2025 (cf. <a href=\"https://www.iiss.org/globalassets/media-library---content--migration/files/publications---free-files/strategic-dossier/pds-2025/chapters/iiss_progress-and-shortfalls-in-europes-defence_2025_ch-3_integrated-air-and-missile-defence.pdf\" target=\"_blank\">Figure 4.1</a>). Cependant, la relation de dépendance est bien moins vraie lorsque cela concerne les missiles de moyenne et courte portées. Les sources d’approvisionnement des pays européens sont en effet plus diverses. Dans le cadre de la European Sky Shield Initiative, la Suède importe non seulement des systèmes Patriot mais aussi des IRIS-T SLM (produits par Diehl) à l’Allemagne. Pour ce qui est des missiles de courtes portée, les pays de l’UE travaillent ensemble pour produire des missiles de courte portée. L’allemand Rheinmetall développe, à cet égard, une nouvelle génération de VSHORAD (very short-range air defence) de la famille du Skyranger. La Pologne a mis en service en 2019 les Piorun, des MANPADS (man-portable air-defence systems), pour remplacer ses Grom. La multiplicité des programmes européens, qu’ils soient strictement nationaux ou collaboratif ne présente pas une faiblesse mais au contraire un atout : ne pas avoir un point unique de défaillance.",
    subtitle5:
    "2. Les fissures et les divergences au sein des alliances ",
    text5:
    "« Il y a fort à parier que dans 15 à 20 ans, la priorité américaine sera leur propre défense et sera beaucoup plus autour de la mer de Chine et dans cette région qu'aux confins de l’Europe ». Comme le signale le président français, l’Europe peut se retrouver seule face aux menaces aériennes. C’est pourquoi elle doit se doter des moyens qui lui sont nécessaires pour sa sécurité et sa défense. Les États-Unis pèsent encore trop dans les sources d’approvisionnement en termes de composante aérienne militaire. Le pays représente en effet 70 % dans le total des moyens militaires dont dispose l’OTAN. Au sein de l’Union européenne, deux approches tentent d’y proposer une réponse. L’approche allemande, illustrée par la European Sky Shield Initiative, propose un armement rapide via des achats aux États-Unis et, en moindre mesure, à Israël. L’Allemagne a montré l’exemple en commandant des missiles exoatmosphériques antibalistiques Arrow 3 à Israël. Afin de réduire la dépendance aux États-Unis, certains pays européens ont révisé leur collaboration industrielle avec le pays, prenant en charge une partie de la production des équipements. C’est le cas de Rheinmetall qui, en créant une coentreprise avec Lockheed Martin, envisage la production de 250 à 300 intercepteur PAC-3. La Pologne et l’Espagne aussi ont commencé à produire des composants pour ce système. Et puis, il y a l’approche française, critique de la première, préconisant une autonomie stratégique et l’instauration d’une véritable base industrielle et technologique pour l’Europe. L’idée est de prioriser les projets communs ou bilatéraux, tels que la France l’entreprend avec l’Italie pour la production de systèmes sol-air de moyenne portée SAMP/T. Concernant l’investissement, l’Europe est à deux vitesses, ce qui entrave les efforts de modernisation des capacités de défense et de dissuasion aérienne de l’Union. « Spending in northern and central Europe grew by 5.5%, while in southern and western Europe it grew by 2.5% » (Béraud-Sudreau, L., & Giegerich, B., 2018). Les pays européens situés à l’ouest et au sud ont éprouvé plus de difficultés à se remettre de la crise de 2008 et des réductions budgétaires liées à la défense.",
    subtitle6:
    "II. Le ressaisissement européen",
    text6:
    "L’Europe fait preuve de réelles intentions pour rattraper son retard dans le domaine de la défense aérienne (A). Les pays du continent doivent construire ensemble une Europe autonome sur les plans industriel et sécuritaire (B).",
    subtitle7:
    "A)L’expression d’intentions et des initiatives européennes vont dans le sens d’une conscience des menaces sécuritaires. <br> 1. Les intentions européennes traduisent une volonté de se moderniser, mais leur exécution subit des délais",
    text7:
    "Avec son Plan de relance (2021), l’Union européenne a prouvé qu’elle était capable d’un endettement commun afin de surmonter des crises telles qu’une pandémie mondiale. La « course technologique » qui se joue en ce moment nécessite des investissements d’autant plus colossaux. En 2025, l’Europe a créé l’instrument Sécurité pour l’action en Europe (SAFE), un fonds d’environ 150 milliards d’euros. L’outil débloque des fonds afin de booster la production industrielle, et notamment celle de missiles défensifs, de systèmes d’artillerie, de munitions, de drones et systèmes antidrone, de facilitateurs stratégiques et d’infrastructures critiques. Dans le white paper European Defence Readiness, la Commission a invité les États membres à activer une clause échappatoire du Pacte de croissance et de stabilité, une disposition qui permettrait aux États d’investir 1,5 point de pourcentage supplémentaire par rapport au PIB dans le domaine de la défense. Cela représente 650 milliards d’euros au total. Les efforts financiers qu’entreprend l’Europe sont observables à travers l’analyse quantitative des contrats passés par les membres de l’OTAN. Entre 2010 et 2017, 50 % des contrats d’acquisition d’« armoured vehicles, multi-role and transport helicopters, tanker and transport aircraft, and artillery » étaient des initiatives de pays d’Europe centrale et du Nord (Béraud-Sudreau, L., & Giegerich, B., 2018). Un délaissement de la composante aérienne militaire représenterait un risque pour tout le continent. L’urgence pour le renforcement sécuritaire aérien est d’autant plus présente que les délais de livraison entravent l’exécution des intentions de modernisation. Par exemple, le projet Next Generation Fighter mené par Dassault et Airbus (Allemagne et Espagne) prévoit une mise en service entre 2035 et 2040. Pour contrecarrer cette lenteur, la Direction générale des Armées a mis en place l’Innovation Defense Lab, un accélérateur d’innovations. En complément, l’Agence d’innovation de défense, instituée en 2018 au sein du ministère des Armées, a pour mission de prioriser la recherche et le développement dans l’intelligence artificielle.",
    subtitle8:
    "2. Un renforcement engagé depuis 2014 qui s’appuie sur les entreprises européennes",
    text8:
    "Les États européens de l’Est font office de tampon entre l’UE et la Russie et sont directement exposés à une attaque potentielle. L’UE doit donc disposer de moyens de dissuasion afin d’influencer le comportement d’acteurs étatiques hostiles. En réaction à l’annexion de la Crimée en 2014, l’UE poursuit son objectif de renforcer sa composante aérienne militaire, en travaillant, par la même occasion, à réduire sa dépendance aux États-Unis en matière de défense et de dissuasion de longue portée. Ainsi, en signe de solidarité sécuritaire envers les pays baltes situés à proximité de la Russie, des pays européens ont évoqué leur souhait de constituer une « police du ciel » en mettant en commun leurs forces aériennes. L’initiative Europe Readiness 2030 a identifié les priorités auxquelles doivent se tenir les pays membres (cf. <a href=\"https://www.iiss.org/publications/strategic-dossiers/progress-and-shortfalls-in-europes-defence-an-assessment/chapter-four-transforming-european-defence-procurement-and-industry/\" target=\"_blank\">Figure 3.1</a>). Quelques-unes concernent les enjeux de la dissuasion et de la défense aérienne notamment : « la défense et les missiles aériens » et « les drones et systèmes antidrones ». Selon l’International Institute for Strategic Studies, sur 16 pays européens membres de l’OTAN, seuls six détiennent plus de six unités appartenant à deux catégories de lanceurs de missiles sol-air différentes. Depuis le recours massif aux drones dans les conflits armés, des entreprises européennes telles que MARSS (groupe soutenu par des capitaux britanniques et saoudiens), Nordic Air Defence en Suède, Origin Robotics en Lettonie se spécialisent dans le secteur des drones. La priorité accordée au développement des drones et systèmes antidrones montre que les entreprises du secteur de la défense jouent un rôle prépondérant, notamment pour la recherche, l’innovation mais aussi pour la production à grande échelle. Les entreprises européennes (Airbus, ArianeGroup, MBDA pour ne citer qu’elles) sont des acteurs incontournables de ces projets collaboratifs. Deux défis s’imposent : celui du progrès (défi temporel), et celui de la collaboration (défi politique). Pour le premier, la Commission européenne préconise, dans sa feuille de route de préparation à l'horizon 2030, de raccourcir les temps de développement afin de simplifier les schémas de production traditionnels. Pour le second défi, l’action de soutien à la production de munitions (ASAP) et le renforcement de l'industrie européenne de la défense par le biais d’acquisitions communes (EDIRPA) visent, en ce sens, à encourager la collaboration et l’approvisionnement collectif en matériel militaire entre les pays membres (y compris la Norvège). La France défend l’instauration d'une base industrielle et technologique européenne. L’idée est d’y développer des technologies de rupture liées à « l’intelligence artificielle, l’hypervélocité, les technologies quantiques ou spatiales ».",
    subtitle9:
    "B) Comment l’Europe peut se protéger <br> Autonomie et cohésion",
    text9:
    "L’interopérabilité reste incontournable pour mener des opérations de dissuasion crédibles. Si l’Europe cherche à se doter de moyens de production spécifiquement européens, elle ne doit cependant pas délaisser le partenariat international otanien. La réponse collective et réactive face à la menace doit passer, selon Guillaume Garnier (chercheur associé au Centre d’études de sécurité de l’IFRI), par une « meilleure coopération OTAN-UE ». Ce dialogue entre UE et OTAN peut prendre la forme de déclarations conjointes comme ce fut le cas en 2023, en 2018 et en 2016. Une nouvelle complémentarité appelée « New Force Model » permettra d’affirmer un véritable « pilier européen » au sein de l’organisation. Il est question pour les membres européens de l’OTAN de devenir des acteurs actifs au sein de l’alliance. Cette volonté de la « double appartenance » a été récemment affirmée par l’intégration de la Suède et de la Finlande. De cette façon, l’Europe saura assurer la défense du continent tout en garantissant son autonomie stratégique.",
    subtitle10:
    "2. L’importance du « left-of-launch »",
    text10:
    "La production de matériel pour la défense et la dissuasion aérienne doit s’accompagner d’une stratégie européenne pour le « left-of-launch », c’est-à-dire les mesures de prévention intervenant avant le lancement de missiles. Il est question d’accorder une importance toute particulière au rôle du renseignement (surveillance, reconnaissance) et d’assurer l’interopérabilité entre les agences du renseignement et les forces aériennes. Cet échange d’information a été un atout pour l’armée israélienne dans le déploiement de sa campagne offensive contre l’Iran. À l’inverse, le manque d’information affecte les efforts en termes de production industrielle : « Russia’s information problem persisted beyond the opening salvos. Targeting plans were created every 24 hours—much too slow to destroy Ukraine’s mobile systems following successful suppression ». L’Europe doit mettre en place une stratégie visant à moderniser et à renforcer ses moyens de collecte et d’analyse du renseignement aérien afin d’établir une véritable stratégie du « left-of-launch ».<br> Les défis auxquels fait face l’Europe sont nombreux. Outre la menace que constitue l’offensive russe en Ukraine, la dépendance que le continent entretient encore à l’égard des États-Unis représente une faiblesse. Les USA sont perçus comme les plus puissants en termes de capacités de défense et de dissuasion aérienne, comme l’a prouvé l’opération au Venezuela non détectée par les radars chinois installés dans le pays. D’autres acteurs pourraient à l’avenir prouver leur puissance dans le domaine, tels que la Corée du Sud, qui a exporté 48 FA-50 en Pologne, le Brésil, qui prévoit d’exporter des KC-390 Millennium vers cinq pays européens. Que ce soit pour ces acteurs étatiques émergents ou l’UE, les terres rares sont primordiales pour la production d’équipements militaires aériens et la dépendance à leur égard constitue un enjeu stratégique majeur. En Europe, l’EU Observatory of Critical Technologies pourrait jouer un rôle dans la définition des matériaux sujets à la dépendance.",
    sources:
    "<li>Béraud-Sudreau, L., & Giegerich, B. (2018). NATO Defence Spending and European Threat Perceptions. Survival, 60(4), 53–74. https://doi.org/10.1080/00396338.2018.1495429 </li><li> Calcara, A., Gilli, A., Gilli, M., Marchetti, R., & Zaccagnini, I. (2022). Why Drones Have Not Revolutionized War: The Enduring Hider-Finder Competition in Air Warfare. International Security, 46(4), 130–171. https://doi.org/10.1162/isec_a_00431 </li><li> Elysée. (2025, January 6). Conférence des ambassadrices et ambassadeurs 2025. <i>elysee.fr</i>. https://www.elysee.fr/emmanuel-macron/2025/01/06/conference-des-ambassadrices-et-ambassadeurs-2025 </li><li>Julia Tomasso. (28 February 2025). Issues of the Iranian Defence Industry and Strategic Choices: Resistance without an Axis? - IRIS. https://www.iris-france.org/en/issues-of-the-iranian-defence-industry-and-strategic-choices-resistance-without-an-axis/ </li><li>La France dans l’OTAN : de l’allié difficile au contributeur essentiel. (n.d.). Ifri. https://www.ifri.org/fr/etudes/la-france-dans-lotan-de-lallie-difficile-au-contributeur-essentiel </li><li>Palmer, A., & Ward, K. (2026). Air Superiority in the Twenty-First Century: Lessons from Iran and Ukraine. https://www.csis.org/analysis/air-superiority-twenty-first-century-lessons-iran-and-ukraine </li><li>Russian air patrols: long-range ambitions. (2015). <i>Strategic Comments</i>, 21(4), iv–v. https://doi.org/10.1080/13567888.2015.1067464 </li><li>The International Institute for Strategic Studies (IISS),  (Ed.). (2025). Progress and Shortfalls in Europe’s Defence: An Assessment (1st ed.). Routledge. https://doi.org/10.4324/9781003715054 </li><li>White paper for European defence - <i>Readiness 2030</i>. (n.d.). Defence Industry and Space. https://defence-industry-space.ec.europa.eu/eu-defence-industry/white-paper-european-defence-readiness-2030_en</li>"    
  },
  {
    id: 4,
    date: "11-03-2026",
    title: "Composantes aériennes (RU-UKR)",
    text: "Analyse et rapports des forces aériennes (perte de drones, inventaires) des deux États engagés dans la guerre menée par la Russie.",
    subtitle1: "Pertes de drones russes (2022-2025)",
    text1:"<div style='text-align:center'><img src='./media/russian_losses.png'></div>",
    subtitle2:"Inventaire de la composante militaire aérienne russe (2026)", 
    text2:"<div style='text-align:center'><img src='./media/RU_inventory.png'></div>",
    subtitle3:'Rapport d\'analyse',
    text3:`===================Analytic report on air force (RUSSIA)===================<br>
      Type : Bomber<br>
      Average age : 58 years old<br>
      Most frequent model : Tu-22M<br><br>

      Type : Combat<br>
      Average age : 37 years old<br>
      Most frequent model : Su-27/30/35<br><br>

      Type : Helicopter<br>
      Average age : 42 years old<br>
      Most frequent model : Mi-8/17/171<br><br>

      Type : Special<br>
      Average age : 47 years old<br>
      Most frequent model : Il-38<br><br>

      Type : Training<br>
      Average age : 39 years old<br>
      Most frequent model : L-39<br><br>

      Type : Transport<br>
      Average age : 47 years old<br>
      Most frequent model : Il-76"<br><br>
      `,
      subtitle4:"Quantité d'unités actives en fonction de leur ancienneté (RU)", 
      text4:"<div style='text-align:center'><img src='./media/ageactivity.png'></div>",
      subtitle5:"Inventaire de la composante militaire aérienne ukrainienne (2026)", 
      text5:"<div style='text-align:center'><img src='./media/UKR_inventory.png'></div>",
      subtitle6:'Rapport d\'analyse',
      text6:`===================Analytic report on air force (UKR)===================<br>
        Type : Combat<br>
        Average age : 42 years old<br>
        Most frequent model : MiG-29<br><br>

        Type : Helicopter<br>
        Average age : 53 years old<br>
        Most frequent model : Mi-8<br><br>

        Type : Special<br>
        Average age : 29 years old<br>
        Most frequent model : Saab 340<br><br>

        Type : Training<br>
        Average age : 54 years old<br>
        Most frequent model : L-39<br><br>

        Type : Transport<br>
        Average age : 60 years old<br>
        Most frequent model : An-24/26<br><br>
      `,
      subtitle7:"Comparison aircrafts categories units",
      text7:"<div style='text-align:center'><img src='./media/comparison.png'></div>",
      sources:"Find the code <a target='_blank' href='https://github.com/Pixeloko/Data-Analysis/blob/main/case-analysis/data.ipynb'>here</a>"
  },
  {
    id: 5,
    date: "12-04-2026",
    title: "Le réveil de L’Asie centrale et sa quête de stabilité régionale",
    text: "Le dernier conflit frontalier d’Asie centrale a pris fin en 2025. Kirghizistan et Tadjikistan se sont mis d’accord sur la délimitation de leur frontière commune, initiant ainsi une période d’apaisement des tensions dans la vallée de Ferghana. Les efforts diplomatiques dont font preuve le Tadjikistan, le Kirghizistan, l’Ouzbékistan, le Kazakhstan et le Turkménistan illustrent une volonté d’apparaître comme une région stable. À l’aune du déclenchement de la guerre russo-ukrainienne, leurs ressources sont d’importance stratégique. L’Europe est en quête d’alternative suite à l’arrêt des gazoducs Nord Stream, lesquels acheminaient 55 milliards de mètres cubes vers l’ouest. Si ce nouveau volume de demande encourage le développement économique des pays centrasiatiques, il ne permet pas aux États de transcender leur dépendance avec la Russie. Afin de conquérir leur autonomie, les gouvernements d’Asie centrale mettent en place des politiques multivectorielles afin de diversifier les partenaires. Comment ces pays concilient-ils leurs relations historiques avec la Russie avec leur doctrine multivectorielle ? La Russie n’est, en effet, plus la seule à s’intéresser à l’Asie centrale (I) puisque ces pays cherchent à s’ouvrir au monde afin d’affirmer leur image de région économiquement émergente et politiquement stable (II).",
    subtitle1: "I/La Russie n’est plus la seule à nouer des relations avec l’Asie centrale ",
    text1:"L’influence Russe sur les pays d’Asie centrale est toujours marquée par les liens historiques (A) mais tend à décroître dans certains État centrasiatique à mesure que la libéralisation politique et économique s’affirme (B).",
    subtitle2:"A)Des relations diverses entre les pays d’Asie centrale et le « Grand frère »", 
    subtitle3:"1.Une relation privilégiée qui s’illustrent encore dans le contexte de la guerre en Ukraine.",
    text3:"À la différence des pays d’Europe de l’Est, les États ex-soviétiques d’Asie centrale ne se sont jamais perçus comme des pays colonisés, mais plutôt comme des satellites de l’URSS (Hiliquin, 2023). De son côté, la Russie considère ces territoires comme faisant partie de son « étranger proche ». La culture et la langue Russe sont encore fortement présentes au sein des sociétés centrasiatiques et les grandes entreprises Russes, telles que Gazprom, pèsent toujours sur l’économie. Leurs ressources énergétiques s’avèrent cruciales pour la Russie en prise aux sanctions internationales. Dans le domaine militaire aussi la Russie reste un acteur de premier plan. Avec le Tadjikistan, le Kazakhstan et le Kirghizistan elle a créé l’Organisation du Traité de Sécurité Collective (OTSC). Il s’agit d’un cadre où les membres se partagent du renseignement et collaborent étroitement sur des questions d’immigration illégale, de terrorisme, d’extrémisme, de trafic de drogue et de crimes organisés. La Russie conserve des positions stratégiques comme au Kirghizistan (base de Kant, laboratoire sismologique) et au Kazakhstan (bases Kostanaï et Baïkonour). De plus, elle interdit toute entrée de flotte militaire étrangère sur la mer caspienne. Les États centrasiatiques ont été doublement impactés par la guerre en Ukraine. Premièrement, du fait des campagnes de recrutement visant les « compatriotes de l’étranger » et les travailleurs centrasiatiques se trouvant sur son sol. Deuxièmement, par l’afflux de migrants Russes, lequel vient atténuer les efforts politiques nationalistes dans un contexte où Vladimir Poutine se positionne en tant que défenseur des Russes de l’étranger. Cela dit, même si ces pays fournissent des ressources stratégiques, aucun ne soutient l’opération russe en Ukraine. Le Kazakhstan respecte les sanctions occidentales tout en ne reconnaissant pas l’indépendance du Donbass ni l’annexion de la Crimée.  Ainsi, à Almaty en 2022 s’est tenue une manifestation contre la guerre, une critique partagée par l’Ouzbékistan. Les deux gouvernements ont permis l’envoi d’aide humanitaire vers l’Ukraine.",
    subtitle4:"2.Nouvelle influence russe au regard des nouveaux enjeux et acteurs en Asie centrale", 
    text4:"Si la Russie s’impose encore comme l’un des principaux partenaires de ces pays, certains États d’Asie centrale ont progressivement révisé leurs rapports avec la puissance. Pour le Kazakhstan, il n’est pas question de rompre radicalement le lien. La Russie représente 11,5 % de ses exportations, 42,1 % de ses importations, les deux pays partagent environ 7 500 km de frontière et l’ethnie russe représente approximativement 20 % de la population kazakhe. De plus, nombreux sont les pays centrasiatiques qui dépendent des envois d’argent de leur diaspora. Cela représente un tiers du PIB du Kirghizistan en 2024. L’idée est alors plutôt de réviser le rapport de force afin d’établir un « équilibre positif », puisque la relation de dépendance s’illustre dans les deux sens : la Russie a besoin des immigrés pour sa main-d’oeuvre. L’exemple le plus évocateur de la volonté d’affirmer sa souveraineté est celui du Kazakhstan. Le pays le plus riche de la région, à travers une holding publique, rachetait en 2022 une filiale Kazakhe de la Sberbank. Ces pays sont en mesure de limiter l’influence Russe et de peser dans les négociations. En 2025, Turmengaz prend la décision de mettre fin à sa collaboration avec Gazprom suite à un différend sur les prix. Une décision qui n’empêche pas pour autant le Turkménistan de continuer d’acheter des équipements militaires et de nouer des partenariats stratégiques (dont un en 2025), avec son « Grand frère ». Sur le plan militaire, l’Ouzbékistan et le Turkménistan ont adopté un comportement de rejet de la domination Russe. Les deux États ne font pas partie de l’OTSC et refusent l’entrée de troupes russes sur leurs territoires suite à la création de la CEI en 1995. Organisation que quitte l’Ouzbékistan en 1999 dans un contexte de perestroïka et de tournant vers l’ouest (l’Ouzbékistan a conclu un accord en 1996 avec les États-Unis permettant l’entraînement des officiers et sous-officiers). Concentrée par d’autres enjeux, la Russie est restée en retrait lors du conflit frontalier en 2022 entre Tadjikistan et Kirghizistan. La Chine a profité de cette distanciation Russe pour investir en Asie centrale. Entre 2000 et 2012, la part de ces pays dans les importations totales de la Russie est passée de 35 % à 13 %, au profit de la Chine. De surcroît, le Kazakhstan autorise en 2024 la construction de deux centrales nucléaires, l’une sera opérée par la Russie, l’autre par la China National Nuclear Corporation ; une décision illustrant la volonté chinoise de se faire une place de choix dans cette région riche en ressources énergétiques.",
    subtitle5:"B.Libéralisation économique et politique de l’Asie centrale",
    subtitle6:"1.La libéralisation tardive au bénéfice d’une relation privilégiée avec l’Occident",
    text6:"À la création du sommet annuel C5+1, en 2015, l’Asie centrale a commencé à dialoguer régulièrement avec l’Occident. La chute du dictateur ouzbek Islam Karimov en 2016 est un symbole de la libéralisation politique en cours à cette période. La nouvelle proximité avec les États-Unis a permis de voir émerger en 2025 des accords sur les minerais critiques et la signature par le Kazakhstan des accords d’Abraham. Sur le plan sociétal, l’usage de l’anglais s’est répandu au sein des nouvelles générations, laissant l’emploi de la langue Russe aux élites politiques. Dans un contexte de jeu d’influences étrangères en Asie centrale, l’UE doit prendre sa place. L’Union y investit déjà au travers de l’Enhanced Partnership and Cooperation Agreement conclu avec le Kazakhstan et de la Global Gateway, une initiative prévoyant 12 milliards d’euros afin de financer des projets liés au transport, aux minerais critiques, aux énergies renouvelables et à la connectivité numérique.",
    subtitle7:"2.Les ressources naturelles de l’Asie centrale, la clé de son ouverture économique au monde",
    text7:"L’accès à l’OMC a été pour trois pays centrasiatiques un symbole d’ouverture au monde. Les stratégies de contournement actuels renforcent d’autant plus l’attractivité de l’Asie centrale, comme le prouve la croissance du PIB de la région, qui est de 5,7 % entre 2023 et 2024. Ces territoires sont riches en ressources énergétiques et en minerais critiques (Le Turkménistan a la quatrième réserve mondiale de GNL). Attirées par celles-ci, la compagnie française Total et ACWA (entreprise publique saoudienne) se sont implantées en Ouzbékistan pour y développer respectivement une centrale solaire et une centrale éolienne. Les économies, notamment ouzbèke et Tadjike sont très dépendantes de leurs ressources énergétiques. Pour limiter le risque de malédiction des ressources, le Kazakhstan conserve un contrôle public dans les domaines critiques (pétrole et gaz) tout en maintenant une doctrine multivectorielle. Si l’Asie centrale attire les capitaux par leurs ressources, elle est aussi le foyer d’accueil de multiples projets de transport. Financé par la Banque Mondiale, le projet CASA-1000 entend faciliter le transport d’hydroélectricité du Tadjikistan et du Kirghizistan vers l’Afghanistan et le Pakistan. Avec ses nouvelles routes de la soie, la Chine souhaite faire de cette région un carrefour pour transporter son fret au-delà de la mer Caspienne. La Chine est devenue le premier partenaire économique des pays centrasiatiques ainsi que le premier acheteur d’uranium. Un lien de dépendance s’est forgé, comme au Kirghizistan où 43 % de la dette est détenue par la Chine (2024). La proximité au sein de cette partie du Sud-Global s’inscrit également sur le plan politique. Quatre des pays d’Asie centrale ont fondé en 2001 l’Organisation de Coopération de Shanghai avec la Chine et la Russie. La place qu’occupe la Chine aujourd’hui amoindrit celle du partenaire historique russe tout en limitant les ambitions des États-Unis, un acteur plus distant. L’illustration du phénomène prend corps dans la perte de monopole de Chevrolet sur le marché de l’automobile Ouzbek lorsqu’est venu s’installer BYD, un constructeur automobile chinois. L’influence chinoise rencontre toutefois des contradictions. En 2018 et 2019 des manifestations anti-chinoises ont eu lieu au Kirghizistan. Les revendications critiquaient la délivrance de passeports aux migrants chinois et réclamaient l’imposition de quotas pour l’embauche des travailleurs chinois. Les populations se montrent critiques de ce qu’il se passe au Xinjiang, du traitement de la communauté ouïghoure, laquelle partage une proximité religieuse avec les sociétés d’Asie centrale.",
    subtitle8:"II/Une volonté de faire de l’Asie centrale une région stable",
    text8:"Dans un contexte de multiples guerres internationales les pays d’Asie centrale veulent prouver qu’ils sont capables de stabiliser la région et d’accueillir des processus de médiation. La croissance économique positive et les politiques multivectorielles mises en place illustrent cette volonté (A). Ces efforts sont toutefois ralentis par des défis tant internes qu’exogènes (B).",
    subtitle9:"A)Construire la stabilité et la « respectabilité »",
    subtitle10:"1.La coopération régionale",
    text10:"Pour mener à bien des projets de collaboration économique, les pays d’Asie centrale se sont d’abord concentrés sur l’apaisement des tensions qui les divisent (accord sur la mer Caspienne 2018 et traité sur la vallée de Ferghana, en 2025). Ainsi, sur la question du partage de l’eau entre l’Ouzbékistan, le Tadjikistan et le Turkménistan, les pays concernés se sont montrés capables de collaborer en engageant des négociations multilatérales et en formulant des accords pour trouver des solutions, comme en 2025 lors d’une rencontre entre le Tadjikistan et l’Ouzbékistan. Depuis 2018, les pays centrasiatiques se rencontrent lors des Sommets consultatifs des chefs d’État pour débattre des enjeux régionaux. Ces canaux diplomatiques rencontrent des succès et renforcent la crédibilité du projet de stabilisation de l’espace centrasiatique. Cette nouvelle stabilité politique repose sur des liens économiques. Comptant pour 60 % du PIB de la région, le Kazakhstan est le leader de cette dynamique. Avec la Russie et la Biélorussie, le pays a institué l’Eurasian Economic Union, une organisation qui envisage la mise en place d’une monnaie unique et d’une zone de libre-échange. Le Kazakhstan contribue activement au dynamisme économique au sein de sa région, au travers d’accords commerciaux, d’investissements et d’envois d’aide au développement (KazAID). On observe une hausse de 15,5 points du taux d’échanges entre le Kazakhstan et l’Ouzbékistan (2024-2025). Les deux pays comptent pour 80 % des échanges au sein de l’Asie centrale. Au-delà des relations bilatérales, les pays centrasiatiques forment des coentreprises, des projets collectifs et se rejoignent au sein d’institutions de coopération telles que l’Intergovernmental Commission on Cooperation. C’est à travers une intégration régionale et l’abandon des arsenaux nucléaires que l’Asie centrale acquiert une « respectabilité internationale » (traduit de l’anglais Frederick Starr & Cornell., 2020)",
    subtitle11:"2.Démontrer la stabilité et la crédibilité",
    text11:"Les États d’Asie centrale sont entourés par des puissances toutes engagées dans des conflits de divers types. Dialoguer avec tous est le principe auquel se tiennent les pays de la région et notamment le Turkménistan qui a choisi la voie de la neutralité et ne fait donc partie d’aucune alliance militaire. Grâce à l’accueil des négociations sur le nucléaire iranien en 2014 et du processus d’Astana en 2017 sur le cas syrien, le Kazakhstan est déjà reconnu comme un médiateur international. À la tribune de l’ONU en 2025, le pays a défendu une application stricte des principes fondamentaux de sa Charte, renforçant son rôle et son image de médiateur. En s’imposant sur la scène internationale, les pays centrasiatiques interrogent le modèle de multilatéralisme de l’ONU, certains revendiquant une réforme du conseil de sécurité afin d’améliorer la représentativité des puissances moyennes.",
    subtitle12:"B)Les défis de l’Asie centrale",
    subtitle13:"1.Défis internes",
    text13:"L’autoritarisme caractérisant certains régimes en Asie centrale présente un obstacle en ce qu’il est l’objet de critiques populaires et religieuses. Des mouvements contestataires et d’autonomisation (Karakalpakstan) naissent sporadiquement et déstabilisent l’ordre interne de ces États. Pour y répondre, les gouvernements enclenchent des répressions, comme ce fut le cas pendant la révolution des tulipes en 2005 ou lors des manifestations anti-guerre de 2022 au Kirghizistan. Face à ces situations, ces pays font encore appel aux puissances étrangères. Ainsi l’OTSC est intervenue au Kazakhstan en réponse aux révoltes de 2022.",
    subtitle14:"2.Défis exogènes",
    text14:"Il existe deux défis externes. Premièrement, celui de l’Afghanistan, particulièrement depuis le retour au pouvoir des talibans. Le territoire voisin représente un point de départ pour le trafic de drogue à destination de l’Europe et de la Russie. Il héberge un foyer influent pour le jihad (État islamique au Khorassan, ISIL-KP). Ce sont des Tadjiks alignés avec l’ISIL-KP qui ont perpétré les attentats au Crocus City Hall de Moscou. De nombreux ressortissants d’Asie centrale ont rejoint les forces qui y sont présentes et le mouvement islamique d’Ouzbékistan (IMU) s’est rallié aux talibans d’Afghanistan en 2015. À la différence de l’IMU, Hizb ut-Tahrir est une organisation politique se revendiquant non violente. Elle est cependant inscrite sur la liste des organisations terroristes du Royaume-Uni et 13 pays l’ont banni, incluant des pays arabes. L’IMU et Hizb ut-Tahrir partagent pour point commun d’être présents en Asie centrale et visent à renverser les gouvernements non islamiques afin d’établir un califat. Faute de capacités sécuritaires, le Tadjikistan a fait appel à la Chine et à la Russie afin d’établir une présence militaire et de surveiller ses voisins talibans. La Chine y perçoit une opportunité, en bénéficiant de cette zone tampon pour prévenir une diffusion islamique vers le Xinjiang. Sans toutefois renier leurs liens avec la Russie, les pays d’Asie centrale adoptent une doctrine multivectorielle dans le but de s’ouvrir au monde et de nouer des relations avec d’autres puissances. À l’échelle régionale, les États collaborent entre eux pour mettre fin aux conflits existants entre eux, ce qui contribue à crédibiliser leur émergence sur la scène internationale en tant qu’acteur intermédiaire. L’influence croissante de la Chine en Asie centrale risque d’amoindrir les efforts de rapprochement mis en place par d’autres puissances telles que l’UE. À cet égard, l’UE doit se montrer compétitive avec ces pays tout en veillant à soutenir leur croissance.",    
    sources:"<li>Pierre, Léo. 2025. ‘L’Asie Centrale, Le Discret Mais Primordial Point Névralgique de La Géopolitique Mondiale’. https://www.slate.fr/monde/asie-centrale-point-nevralgique-essentiel-economie-geopolitique-energie-commerce-europe-chine-russie-guerre-ukraine.</li><li>Yégavian, Tigrane. 2022. ‘L’Asie Centrale, Terrain de Jeu de La Rivalité Sino-Russe’. https://archive.is/20230323020954/https://www.revueconflits.com/lasie-centrale-terrain-de-jeu-de-la-rivalite-sino-Russe/#selection-1151.1-1151.58.</li><li>Levystone, Michaël. 2020. ‘L’Asie Centrale Au Chevet d’un Multilatéralisme Vacillant ?’ Notes de l’Observatoire. https://observatoire-eurasie.fr/notes-de-lobservatoire/lasie-centrale-au-chevet-dun-multilateralisme-vacillant/.</li><li>Frederick Starr et Cornell. 2020. ‘Kazakhstan’s Role in International Mediation under First President Nursultan Nazarbayev’. Central Asia-Caucus Institute Silk Road Studies Program.</li><li>Balci. 2025. ‘Le Déclin de La Russie En Asie Centrale’. Revue de Culture Contemporaine 19–31.</li><li>Prime Minister of the Republic of Kazakhstan. 2023. Kazakhstan and Uzbekistan Sign Intergovernmental Commission on Central Asia Roadmap to Accelerate Its Establishment. https://primeminister.kz/en/news/Kazakhstan-and-uzbekistan-sign-intergovernmental-commission-on-central-asia-roadmap-to-accelerate-its-establishment-24005.</li>"
  }

];

export { articles };